force-app/main/default/objects/Salesorder__c/Salesorder__c.object-meta.xml
<CustomObject>
    <label>Salesorder</label>
    <nameField>
        <displayFormat>SO-{000}</displayFormat>
        <label>Salesorder No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesorders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesorderLineProduct__c/SalesorderLineProduct__c.object-meta.xml
<CustomObject>
    <label>SalesorderLineProduct</label>
    <nameField>
        <displayFormat>SLiP-{000}</displayFormat>
        <label>SalesorderLine Product  No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesorderLineProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesorderLineProduct__c/fields/Salesorder_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesorder_Name__c</fullName>
    <label>Salesorder Name</label>
    <referenceTo>Salesorder__c</referenceTo>
    <relationshipLabel>SalesorderLineProducts</relationshipLabel>
    <relationshipName>SalesorderLineProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MultipleProductsController.cls
public class MultipleProductsController {
    public List<SalesorderLineProduct__c> slp{get; set;}
    public Salesorder__c sc{get; set;}
    public String scId {get; set;}
    public MultipleProductsController(){
        sc = new Salesorder__c();
        slp = new List<SalesorderLineProduct__c>();
        sc.Id=ApexPages.currentPage().getParameters().get('id');
        
    }
    public PageReference saveProducts() {
        if (sc != null) {
        for (SalesorderLineProduct__c p : slp) {
            p.Salesorder_Name__c = sc.Id;
        }
        }
        if (!slp.isEmpty()) {
        insert slp;
        }
        PageReference pf = new PageReference('/'+sc.Id);
        return pf;
    }
    public void addProducts() {
        slp.add(new SalesorderLineProduct__c());
    }    
    public PageReference cancel(){
        PageReference pf = new PageReference('/'+sc.Id);
        return pf;
    }
}