force-app/main/default/objects/InvoiceLineProduct__c/InvoiceLineProduct__c.object-meta.xml
<CustomObject>
    <label>InvoiceLineProduct</label>
    <nameField>
        <displayFormat>ILP-{000}</displayFormat>
        <label>Invoice Line Product  No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InvoiceLineProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineProduct__c/fields/Sales_orderline_item__c.field-meta.xml
<CustomField>
    <fullName>Sales_orderline_item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales-orderline item</label>
    <referenceTo>SalesorderLineProduct__c</referenceTo>
    <relationshipLabel>InvoiceLineProducts</relationshipLabel>
    <relationshipName>InvoiceLineProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesorderLineProduct__c/SalesorderLineProduct__c.object-meta.xml
<CustomObject>
    <label>SalesorderLineProduct</label>
    <nameField>
        <displayFormat>SLiP-{000}</displayFormat>
        <label>SalesorderLine Product  No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesorderLineProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoiceLineProductTriggerHandler.cls
public class InvoiceLineProductTriggerHandler {
    public static void handleBalancedquantity(list<InvoiceLineProduct__c> invlist){
        list<SalesorderLineProduct__c> updsales= new list<SalesorderLineProduct__c>();
        
        list<id> salesupdate= new list<id>();
        for(InvoiceLineProduct__c aa: invlist){
            if(aa.Sales_orderline_item__c!= null){
                salesupdate.add(aa.Sales_orderline_item__c);
            }
        }
        for(SalesorderLineProduct__c ss: [select id,Invoiced_Quantity__c from SalesorderLineProduct__c where Id IN :salesupdate]){
            decimal quantity= 0;
              for(InvoiceLineProduct__c ic: [select id, Quantity__c from InvoiceLineProduct__c where Sales_orderline_item__c = :ss.id]){
                 quantity= quantity + ic.Quantity__c; 
           }
            ss.Invoiced_Quantity__c = quantity;
            updsales.add(ss);
       }
        update updsales;
    }      
}