force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Invoice-{000}</displayFormat>
        <label>Invoice No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Salesorder__c.field-meta.xml
<CustomField>
    <fullName>Salesorder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesorder</label>
    <referenceTo>Salesorder__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineProduct__c/InvoiceLineProduct__c.object-meta.xml
<CustomObject>
    <label>InvoiceLineProduct</label>
    <nameField>
        <displayFormat>ILP-{000}</displayFormat>
        <label>Invoice Line Product  No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InvoiceLineProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineProduct__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>%</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceLineProduct__c/fields/Invoice_Name__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Name__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>InvoiceLineProducts</relationshipLabel>
    <relationshipName>InvoiceLineProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineProduct__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunitiescustom__c</referenceTo>
    <relationshipLabel>InvoiceLineProducts</relationshipLabel>
    <relationshipName>InvoiceLineProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>InvoiceLineProducts</relationshipLabel>
    <relationshipName>InvoiceLineProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineProduct__c/fields/Sales_order_Name__c.field-meta.xml
<CustomField>
    <fullName>Sales_order_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales-order Name</label>
    <referenceTo>Salesorder__c</referenceTo>
    <relationshipLabel>InvoiceLineProducts</relationshipLabel>
    <relationshipName>InvoiceLineProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineProduct__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>( Discounted_Price__c  +  CGST_Amount__c  +  IGST_Amount__c  +  SGST_Amount__c )  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <displayFormat>Product-{000}</displayFormat>
        <label>Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesorder__c/Salesorder__c.object-meta.xml
<CustomObject>
    <label>Salesorder</label>
    <nameField>
        <displayFormat>SO-{000}</displayFormat>
        <label>Salesorder No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesorders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesorder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Salesorders</relationshipLabel>
    <relationshipName>Salesorders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salesorder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Salesorders</relationshipLabel>
    <relationshipName>Salesorders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesorderLineProduct__c/SalesorderLineProduct__c.object-meta.xml
<CustomObject>
    <label>SalesorderLineProduct</label>
    <nameField>
        <displayFormat>SLiP-{000}</displayFormat>
        <label>SalesorderLine Product  No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesorderLineProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesorderLineProduct__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunitiescustom__c</referenceTo>
    <relationshipLabel>SalesorderLineProducts</relationshipLabel>
    <relationshipName>SalesorderLineProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesorderLineProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>SalesorderLineProducts</relationshipLabel>
    <relationshipName>SalesorderLineProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesorderLineProduct__c/fields/Salesorder_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesorder_Name__c</fullName>
    <label>Salesorder Name</label>
    <referenceTo>Salesorder__c</referenceTo>
    <relationshipLabel>SalesorderLineProducts</relationshipLabel>
    <relationshipName>SalesorderLineProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesorderLineProduct__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>(Discounted_Price__c  +  CGST_Amount__c  +  IGST_Amount__c  +  SGST_Amount__c )  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CreateInvoiceController.cls
public class CreateInvoiceController {
    
    public list<SalesorderLineProduct__c> lislip{get;set;}
    public Salesorder__c s{get;set;}
    public List<InvoiceLineProduct__c> invoiceLineItems { get; set; }
    public InvoiceLineProduct__c ilip{get; set;}
    public Invoice__c i{get; set;}
    public String sId{get; set;}
    
    public CreateInvoiceController() {
        s = new Salesorder__c();
        i = new Invoice__c();
        lislip=new list<SalesorderLineProduct__c>();
        ilip = new InvoiceLineProduct__c();
        invoiceLineItems = new List<InvoiceLineProduct__c>();
        sId=ApexPages.currentPage().getParameters().get('id');
        
        lislip = [
            SELECT Id, Name, Discount_Type__c,Discount_Value__c, Quantity__c, Actual_Price__c, Unit_Price__c, Opportunity_Name__c, Product__c, Total_Price__c,SalesorderLineProduct__c.Salesorder_Name__c
            FROM SalesorderLineProduct__c
            WHERE Salesorder_Name__c = :sId
        ];
        s = [SELECT Name,Account__c, Contact__c, Account__r.Name, Contact__r.Name
                           FROM Salesorder__c WHERE Salesorder__c.id = :sId LIMIT 1];
    }
    public PageReference cancel(){
        PageReference pf = new PageReference('/'+sId);
        return pf;
    }
    public PageReference save() {
        i.Salesorder__c= s.id;
        i.Account__c=s.Account__r.id;
        i.Contact__c= s.Contact__r.id;
        insert i;
        for(SalesorderLineProduct__c cc: lislip)
        {
            ilip = new InvoiceLineProduct__c();
            ilip.Invoice_Name__c = i.id;
            ilip.Sales_order_Name__c = cc.Salesorder_Name__c;
            ilip.Product__c = cc.Product__c;
            ilip.Quantity__c = cc.Quantity__c;
            ilip.Unit_Price__c = cc.Unit_Price__c;
            invoiceLineItems.add(ilip);
        }
        upsert ilip;
        PageReference pf = new PageReference('/'+sId);
        return pf;
    }
        
}