force-app/main/default/objects/Opportunitiescustom__c/Opportunitiescustom__c.object-meta.xml
<CustomObject>
    <label>Opportunitiescustom</label>
    <nameField>
        <displayFormat>O-{000}</displayFormat>
        <label>Opportunity No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunitiescustom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunitiescustom__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunitiescustom</relationshipLabel>
    <relationshipName>Opportunitiescustom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApexClsLWC.cls
public class ApexClsLWC {
  @AuraEnabled(cacheable=true)
  public static List<Account> getAccounts(String actName) {
    List<Account> accountList = new List<Account>();
    if (actName != '') {
      String accountName = '%' + actName + '%';
      accountList = [SELECT Id, Name FROM Account WHERE Name LIKE :accountName];
    }
    return accountList;
  }
  @AuraEnabled
  public static void createOpp(String email, Id AccountId, Date CloseDate) {
    Opportunitiescustom__c opp = new Opportunitiescustom__c(
      Email__c = email,
      Account_Name__c = AccountId,
      Close_Date__c = CloseDate
    );
    insert opp;
  }
}