force-app/main/default/objects/Opportunitiescustom__c/Opportunitiescustom__c.object-meta.xml
<CustomObject>
    <label>Opportunitiescustom</label>
    <nameField>
        <displayFormat>O-{000}</displayFormat>
        <label>Opportunity No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunitiescustom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunitiescustom__c/fields/NameWithTimestamp__c.field-meta.xml
<CustomField>
    <fullName>NameWithTimestamp__c</fullName>
    <label>NameWithTimestamp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityCustomTriggerHandler.cls
public class OpportunityCustomTriggerHandler {
    public static void updateNameWithTimeStamp(List<Opportunitiescustom__c> newOppList){
        List<Opportunitiescustom__c> recordsToUpdate = new List<Opportunitiescustom__c>();
        DateTime timestamp = DateTime.now();
        String formattedTimeStamp = timestamp.format('dd/MM/yyyy');
        for(Opportunitiescustom__c opp: [SELECT Id,Name,NameWithTimestamp__c FROM Opportunitiescustom__c WHERE Id IN :newOppList])
        {
            opp.NameWithTimestamp__c = opp.Name + '-' + formattedTimeStamp;
            System.debug(opp.NameWithTimestamp__c);
            recordsToUpdate.add(opp);
        }
        update recordsToUpdate;
    }
        
}