force-app/main/default/objects/Opportunitiescustom__c/Opportunitiescustom__c.object-meta.xml
<CustomObject>
    <label>Opportunitiescustom</label>
    <nameField>
        <displayFormat>O-{000}</displayFormat>
        <label>Opportunity No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunitiescustom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItems__c/OpportunityLineItems__c.object-meta.xml
<CustomObject>
    <label>OpportunityLineItems</label>
    <nameField>
        <displayFormat>OPLI-{000}</displayFormat>
        <label>OPLI No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItems__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunitiescustom__c</referenceTo>
    <relationshipLabel>OpportunityLineItems</relationshipLabel>
    <relationshipName>OpportunityLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AddProducts.cls
public class AddProducts {
    public List<OpportunityLineItems__c> pro{get; set;}
    public Opportunitiescustom__c oppc{get; set;}
    public String oppId {get; set;}
    public AddProducts(){
        oppc = new Opportunitiescustom__c();
        pro = new List<OpportunityLineItems__c>();
        oppc.Id=ApexPages.currentPage().getParameters().get('id');
        
    }
    public PageReference saveProducts() {
        if (oppc != null) {
        for (OpportunityLineItems__c p : pro) {
            p.Opportunity_Name__c = oppc.Id;
        }
        }
        if (!pro.isEmpty()) {
        insert pro;
        }
        PageReference pf = new PageReference('/'+oppc.Id);
        return pf;
    }
    public void addProducts() {
        pro.add(new OpportunityLineItems__c());
    }    
    public PageReference cancel(){
        PageReference pf = new PageReference('/'+oppc.Id);
        return pf;
    }
}