force-app/main/default/objects/Opportunitiescustom__c/Opportunitiescustom__c.object-meta.xml
<CustomObject>
    <label>Opportunitiescustom</label>
    <nameField>
        <displayFormat>O-{000}</displayFormat>
        <label>Opportunity No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunitiescustom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunitiescustom__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunitiescustom</relationshipLabel>
    <relationshipName>Opportunitiescustom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunitiescustom__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunitiescustom</relationshipLabel>
    <relationshipName>Opportunitiescustom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunitiescustom__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Generated</fullName>
            </value>
            <value>
                <fullName>Need Analysis</fullName>
            </value>
            <value>
                <fullName>Quote Submitted</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/sendemailfromopp.cls
public class sendemailfromopp {
    
    public List<sendemailfromoppwrap> oppwrap{get;set;}
    public List<Opportunitiescustom__c> opp{get;set;}
    public integer indexno{get;set;}
    
    public sendemailfromopp(){
        oppwrap = new List<sendemailfromoppwrap>();
        opp= new List<Opportunitiescustom__c>();
        for(Opportunitiescustom__c o: [Select id,Name,Account_Name__r.Name,Stage__c,Contact_Name__r.Email,Close_Date__c,OwnerId,Email__c from Opportunitiescustom__c]){
            oppwrap.add(new sendemailfromoppwrap(o));
        }
    }
    
    public class sendemailfromoppwrap{
        
        public boolean checkbox{get;set;}
        public Opportunitiescustom__c addedopp{get;set;}
        
        public sendemailfromoppwrap(Opportunitiescustom__c opp){
            checkbox = false;
            addedopp= opp;
        }
    }
    
    public void add(){
        for(sendemailfromoppwrap o: oppwrap){
            if(o.checkbox==true){
                opp.add(o.addedopp);
            }
            o.checkbox=false;
        }
    }
    
    public void send(){
        if(opp.size()>0){
            Messaging.SingleEmailMessage msg= new Messaging.SingleEmailMessage();
            for(Opportunitiescustom__c o :opp){
                String[] toAddress = new String[]{o.email__c};
                String[] ccAddress = new String[]{'pasupulatink@gmail.com'};
                msg.setToAddresses(toAddress);
                msg.setCcAddresses(ccAddress);
                msg.setSubject('Opportuntiy Details'); 
                msg.sethtmlBody('Hi '+'<br></br> Below are your opportunity details- <br></br> Name= '+o.name+
                                '<br></br> Email= '+o.Email__c+'<br></br> Close Date= '+o.Close_Date__c);
                messaging.sendEmail(new Messaging.singleEmailMessage[]{msg});
            }
            ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.CONFIRM,'Email sent successfully'));
        }
        else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.Severity.WARNING,'No records selected. Please Seleted some record and then send email'));
        }
    }
    
    public pageReference Cancel(){
        pageReference pg = new pageReference('/lightning/o/Opportunity_Management__c/list?filterName=Recent');
        return pg;
    }
    
    public void deleteIt(){
        opp.remove(indexno-1);
    }
    
}