force-app/main/default/objects/Opportunitiescustom__c/Opportunitiescustom__c.object-meta.xml
<CustomObject>
    <label>Opportunitiescustom</label>
    <nameField>
        <displayFormat>O-{000}</displayFormat>
        <label>Opportunity No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunitiescustom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotes__c/Quotes__c.object-meta.xml
<CustomObject>
    <label>Quotes</label>
    <nameField>
        <displayFormat>Quote-{000}</displayFormat>
        <label>Quote No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Opportunitiescustom__c.field-meta.xml
<CustomField>
    <fullName>Opportunitiescustom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunitiescustom</label>
    <referenceTo>Opportunitiescustom__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Quote_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_Date__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/QuotePDFController.cls
public class QuotePDFController {
    public List<Quotes__c> quLi{get;set;}
    public Quotes__c qu{get;set;}
    public String accId{get;set;}
    public Account ac{get;set;}
    
    public QuotePDFController(){
        qu= new Quotes__c();
        qu=[select ID, Name, Account__c,Contact__c, Delivery_Lead_Time__c, Opportunitiescustom__c, Payment_terms__c, Quote_Date__c, Remarks__c,Valid_Till__c, Warranty__c 
              from Quotes__c WHERE ID=: ApexPages.currentPage().getParameters().get('Id') limit 1];
        accId= qu.Account__c;
        ac = [SELECT Id, Name, BillingStreet, ShippingStreet, BillingCity, ShippingCity, BillingPostalCode, ShippingPostalCode, BillingState, ShippingState  FROM Account WHERE Id = :accId LIMIT 1];
    
    }

    public List<Quotes__c> getQuotesList(){
        return quLi;
        
    }
}