force-app/main/default/objects/Opportunitiescustom__c/Opportunitiescustom__c.object-meta.xml
<CustomObject>
    <label>Opportunitiescustom</label>
    <nameField>
        <displayFormat>O-{000}</displayFormat>
        <label>Opportunity No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunitiescustom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItems__c/OpportunityLineItems__c.object-meta.xml
<CustomObject>
    <label>OpportunityLineItems</label>
    <nameField>
        <displayFormat>OPLI-{000}</displayFormat>
        <label>OPLI No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItems__c/fields/Actual_Price__c.field-meta.xml
<CustomField>
    <fullName>Actual_Price__c</fullName>
    <label>Actual Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItems__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunitiescustom__c</referenceTo>
    <relationshipLabel>OpportunityLineItems</relationshipLabel>
    <relationshipName>OpportunityLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EditAllOpportunityLineItemsController.cls
public class EditAllOpportunityLineItemsController {

    public Integer myvar { get; set; }
    public Opportunitiescustom__c oppc{get; set;}
    public List<OpportunityLineItems__c> relatedOppLi { get; set; }
    public Integer num{get; set;}
    public String oppId { get; set; }
    public integer index{get; set;}
    
    public EditAllOpportunityLineItemsController() {
        oppc = new Opportunitiescustom__c();
        relatedOppLi = new List<OpportunityLineItems__c>();
        oppc.Id = ApexPages.currentPage().getParameters().get('id');
        relatedOppLi = [
            SELECT Id, Name, Discount_Type__c,Discount_Value__c, Quantity__c, Actual_Price__c, Unit_Price__c, Opportunity_Name__r.Name
            FROM OpportunityLineItems__c
            WHERE Opportunity_Name__c = :oppc.Id
        ];
    }
    public PageReference updateOppLi(){
        update relatedOppLi;
        PageReference pf = new PageReference('/'+oppc.Id);
        return pf;
    }
    public PageReference cancel(){
        PageReference pf = new PageReference('/'+oppc.Id);
        return pf;
    }
    public PageReference del(){
        delete relatedOppLi[index];
        PageReference pf=new PageReference('/apex/EditAllOpportunityLineItems?id=' + oppc.Id);
        pf.setRedirect(True);
        return pf;        
    }

}