force-app/main/default/objects/Opportunitiescustom__c/Opportunitiescustom__c.object-meta.xml
<CustomObject>
    <label>Opportunitiescustom</label>
    <nameField>
        <displayFormat>O-{000}</displayFormat>
        <label>Opportunity No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunitiescustom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunitiescustom__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunitiescustom</relationshipLabel>
    <relationshipName>Opportunitiescustom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccConOpp.cls
public class AccConOpp {
    public Account newAccount { get; set; }
    public Contact newContact { get; set; }
    public Opportunitiescustom__c newOpportunity { get; set; }
    
    public AccConOpp() {
        newAccount = new Account();
        newContact = new Contact();
        newOpportunity = new Opportunitiescustom__c();
    }
    public pagereference SaveIt(){
            insert newAccount;
            newContact.AccountId = newAccount.Id;
            insert newContact;
            newOpportunity.Account_Name__c = newAccount.Id;
            insert newOpportunity;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Records saved successfully.'));
            pagereference pf=new pagereference('/'+newAccount.Id);
            return pf;
                
        }
    public PageReference cancelAction() {
        return new PageReference('/apex/AccConOpp'); 
    }
}