force-app/main/default/objects/Opportunitiescustom__c/Opportunitiescustom__c.object-meta.xml
<CustomObject>
    <label>Opportunitiescustom</label>
    <nameField>
        <displayFormat>O-{000}</displayFormat>
        <label>Opportunity No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunitiescustom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunitiescustom__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunitiescustom</relationshipLabel>
    <relationshipName>Opportunitiescustom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunitiescustom__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunitiescustom</relationshipLabel>
    <relationshipName>Opportunitiescustom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccConOpp2.cls
public with sharing class AccConOpp2 {
  @AuraEnabled
  public static void createAccountContactOpportunity(
    Account account,
    Contact contact,
    Opportunitiescustom__c opportunity
  ) {
    try {
      insert account;
      contact.AccountId = account.Id;
      insert contact;
      opportunity.Account_Name__c = account.Id;
      opportunity.Contact_Name__c = contact.Id;
      insert opportunity;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}