force-app/main/default/objects/Opportunitiescustom__c/Opportunitiescustom__c.object-meta.xml
<CustomObject>
    <label>Opportunitiescustom</label>
    <nameField>
        <displayFormat>O-{000}</displayFormat>
        <label>Opportunity No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunitiescustom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunitiescustom__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunitiescustom</relationshipLabel>
    <relationshipName>Opportunitiescustom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/Quotes__c.object-meta.xml
<CustomObject>
    <label>Quotes</label>
    <nameField>
        <displayFormat>Quote-{000}</displayFormat>
        <label>Quote No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotes__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Opportunitiescustom__c.field-meta.xml
<CustomField>
    <fullName>Opportunitiescustom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunitiescustom</label>
    <referenceTo>Opportunitiescustom__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Quote_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_Date__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CreateQuoteController.cls
public class CreateQuoteController {

    public Id oppId { get; set; }
    public Quotes__c quote { get; set; }
    public Opportunitiescustom__c oppc{get; set;}
    public List<Quotes__c > relatedQuotes { get; set; }

    public CreateQuoteController () {
        oppId = ApexPages.CurrentPage().getParameters().get('oppId');
        quote = new Quotes__c(Opportunitiescustom__c = oppId);
        relatedQuotes = new List<Quotes__c >();
        relatedQuotes = [
            SELECT Id, Name, Account__r.Name, Contact__r.Name, Delivery_Lead_Time__c, Payment_terms__c, Quote_Date__c, Remarks__c, Valid_Till__c, Warranty__c, Opportunitiescustom__r.Name
            FROM Quotes__c 
            WHERE Opportunitiescustom__c = :oppId
        ];
    }
    public PageReference save() {
            insert quote;
            PageReference pf = new PageReference('/'+quote.Id);
            return pf;
    }
    public PageReference cancel() {
        PageReference pf = new PageReference('/'+oppId );
        return pf;
    }
}