force-app/main/default/objects/Opportunitiescustom__c/Opportunitiescustom__c.object-meta.xml
<CustomObject>
    <label>Opportunitiescustom</label>
    <nameField>
        <displayFormat>O-{000}</displayFormat>
        <label>Opportunity No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunitiescustom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunitiescustom__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunitiescustom</relationshipLabel>
    <relationshipName>Opportunitiescustom</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunitiescustom__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunitiescustom</relationshipLabel>
    <relationshipName>Opportunitiescustom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunitiescustom__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Generated</fullName>
            </value>
            <value>
                <fullName>Need Analysis</fullName>
            </value>
            <value>
                <fullName>Quote Submitted</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccConOppAuraEnabled.cls
public with sharing class AccConOppAuraEnabled {
  @AuraEnabled
  public static Id createAccount(
    String Name,
    String Phone,
    String Website,
    String Industry,
    String Description,
    String Rating
  ) {
    Account acc = new Account(
      Name = Name,
      Phone = Phone,
      Website = Website,
      Industry = Industry,
      Description = Description,
      Rating = Rating
    );
    insert acc;
    return acc.Id;
  }

  @AuraEnabled
  public static Id createContact(
    String FirstName,
    String LastName,
    Id AccountId,
    String Phone,
    String Email,
    String Title
  ) {
    if (Phone != null && Phone.length() != 10) {
      throw new AuraHandledException('Phone number must be 10 digits');
    }
    if (Phone == null && Email == null) {
      throw new AuraHandledException('Phone & Email both cannot be blank');
    }
    Contact con = new Contact(
      AccountId = AccountId,
      FirstName = FirstName,
      LastName = LastName,
      Phone = Phone,
      Email = Email,
      Title = Title
    );
    insert con;
    return con.Id;
  }

  @AuraEnabled
  public static void createOpportunity(
    String Name,
    String StageName,
    Id ContactId,
    Date CloseDate,
    Id AccountId
  ) {
    Opportunitiescustom__c opp = new Opportunitiescustom__c(
      Contact_Name__c = ContactId,
      Stage__c = StageName,
      Close_Date__c = CloseDate,
      Account_Name__c = AccountId
    );
    insert opp;
  }
}