force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>Inventory-{000}</displayFormat>
        <label>Inventory No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InventoryHistory__c/InventoryHistory__c.object-meta.xml
<CustomObject>
    <label>InventoryHistory</label>
    <nameField>
        <displayFormat>InvHist-{000}</displayFormat>
        <label>Inventory History No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InventoryHistory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InventoryHistory__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>InventoryHistory</relationshipLabel>
    <relationshipName>InventoryHistory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InventoryHistory__c/fields/Invoice_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>InvoiceLineProduct__c</referenceTo>
    <relationshipLabel>InventoryHistory</relationshipLabel>
    <relationshipName>InventoryHistory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InventoryHistory__c/fields/Invoiced_Line_Item_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_Line_Item_Quantity__c</fullName>
    <label>Invoiced Line Item Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InventoryHistory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>InventoryHistory</relationshipLabel>
    <relationshipName>InventoryHistory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Invoice-{000}</displayFormat>
        <label>Invoice No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineProduct__c/InvoiceLineProduct__c.object-meta.xml
<CustomObject>
    <label>InvoiceLineProduct</label>
    <nameField>
        <displayFormat>ILP-{000}</displayFormat>
        <label>Invoice Line Product  No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InvoiceLineProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineProduct__c/fields/Invoice_Name__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Name__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>InvoiceLineProducts</relationshipLabel>
    <relationshipName>InvoiceLineProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>InvoiceLineProducts</relationshipLabel>
    <relationshipName>InvoiceLineProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <displayFormat>Product-{000}</displayFormat>
        <label>Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/inventoryHistoryHandlerClass.cls
public class inventoryHistoryHandlerClass {
    public static void createInventoryHistoryFromInvoiceLineProduct(list<InvoiceLineProduct__c> invlist){
        
        Set<Id> iliIds= new Set<Id>();
        for(InvoiceLineProduct__c il: invlist){
        	iliIds.add(il.Id);
        }
        List<InvoiceLineProduct__c> iliList2= [Select Id, Invoice_Name__r.Ware_House__c, Product__c, Quantity__c from InvoiceLineProduct__c where Id in: iliIds];
      	List<InventoryHistory__c> ihLi = new List<InventoryHistory__c>();
        for(InvoiceLineProduct__c ilp : invlist){
            InventoryHistory__c ih = new InventoryHistory__c();
            ih.Product__c = ilp.Product__c;
            ih.Invoice_Line_Item__c = ilp.id;
            ih.Invoiced_Line_Item_Quantity__c = ilp.Quantity__c;
            Id warehouseId= ilp.Invoice_Name__r.Ware_House__c;
            Id productId= ilp.Product__c;
            Inventory__c inventory= [Select Id from Inventory__c where Product__c=: productId And Warehouse__c=:warehouseId];
            ih.Inventory__c= inventory.id;
            ihLi.add(ih);
        }
       
        if(!ihLi.isEmpty()){
			insert ihLi;
        } 
    }
}