force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>Inventory-{000}</displayFormat>
        <label>Inventory No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InventoryHistory__c/InventoryHistory__c.object-meta.xml
<CustomObject>
    <label>InventoryHistory</label>
    <nameField>
        <displayFormat>InvHist-{000}</displayFormat>
        <label>Inventory History No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InventoryHistory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InventoryHistory__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>InventoryHistory</relationshipLabel>
    <relationshipName>InventoryHistory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InventoryHistory__c/fields/Invoice_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>InvoiceLineProduct__c</referenceTo>
    <relationshipLabel>InventoryHistory</relationshipLabel>
    <relationshipName>InventoryHistory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InventoryHistory__c/fields/Invoiced_Line_Item_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_Line_Item_Quantity__c</fullName>
    <label>Invoiced Line Item Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InventoryHistory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>InventoryHistory</relationshipLabel>
    <relationshipName>InventoryHistory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Invoice-{000}</displayFormat>
        <label>Invoice No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoiced_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_Quantity__c</fullName>
    <label>Invoiced Quantity</label>
    <summarizedField>InvoiceLineProduct__c.Quantity__c</summarizedField>
    <summaryFilterItems>
        <field>InvoiceLineProduct__c.Quantity__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoiceLineProduct__c.Invoice_Name__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineProduct__c/InvoiceLineProduct__c.object-meta.xml
<CustomObject>
    <label>InvoiceLineProduct</label>
    <nameField>
        <displayFormat>ILP-{000}</displayFormat>
        <label>Invoice Line Product  No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InvoiceLineProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineProduct__c/fields/Invoice_Name__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Name__c</fullName>
    <label>Invoice Name</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>InvoiceLineProducts</relationshipLabel>
    <relationshipName>InvoiceLineProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>InvoiceLineProducts</relationshipLabel>
    <relationshipName>InvoiceLineProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLineProduct__c/fields/Sales_orderline_item__c.field-meta.xml
<CustomField>
    <fullName>Sales_orderline_item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales-orderline item</label>
    <referenceTo>SalesorderLineProduct__c</referenceTo>
    <relationshipLabel>InvoiceLineProducts</relationshipLabel>
    <relationshipName>InvoiceLineProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <displayFormat>Product-{000}</displayFormat>
        <label>Product No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesorderLineProduct__c/SalesorderLineProduct__c.object-meta.xml
<CustomObject>
    <label>SalesorderLineProduct</label>
    <nameField>
        <displayFormat>SLiP-{000}</displayFormat>
        <label>SalesorderLine Product  No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesorderLineProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesorderLineProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>SalesorderLineProducts</relationshipLabel>
    <relationshipName>SalesorderLineProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/salesorderToInvoiceHelperUpdate.cls
public class salesorderToInvoiceHelperUpdate {
    public static void InvoicedQty(List<InvoiceLineProduct__c> invListItm){
    	
        //To update Invoiced quantity on Sales_orderline_item__c
        Map<id, decimal> soliToQuanity = new Map<id,decimal>();
        Set<id> salesid = new Set<id>();
        Set<id> invoiceId = new Set<id>();
        for(InvoiceLineProduct__c inv : invListItm){
            if(inv.Sales_orderline_item__c != null){
                soliToQuanity.put(inv.Sales_orderline_item__c, inv.Quantity__c);
                salesid.add(inv.Sales_orderline_item__c);
                invoiceId.add(inv.Invoice_Name__c);
                system.debug(inv.Product__c);
            }
        }
        
		List<SalesorderLineProduct__c> sales = new List<SalesorderLineProduct__c>([Select id,Invoiced_Quantity__c from SalesorderLineProduct__c where id in: salesid]);
        
        for(SalesorderLineProduct__c soli : sales){
            decimal quantity = soli.Invoiced_Quantity__c;
            quantity += soliToQuanity.get(soli.id);
            soli.Invoiced_Quantity__c = quantity;
        }
        update sales;
        
        //To create inventory history
        Map<id, Invoice__c> invoiceMap = new Map<id, Invoice__c>([Select id, name,Ware_House__c from Invoice__c where id in : invoiceId]);
        List<InventoryHistory__c> inventhistory= new List<InventoryHistory__c>();
        
        for (InvoiceLineProduct__c inv : invListItm) {
            Invoice__c invoice = invoiceMap.get(inv.Invoice_Name__c);
            if (invoice != null) {
                Inventory__c inventory = [SELECT Id, Name FROM Inventory__c WHERE Warehouse__c =: invoice.Ware_House__c AND Product__c =: inv.Product__c];
                if (inventory != null) {
                    InventoryHistory__c newInventoryHistory = new InventoryHistory__c(
                        Invoiced_Line_Item_Quantity__c = inv.Quantity__c,
                        Invoice_Line_item__c = inv.Id,
                        Inventory__c = inventory.Id,
                        Product__c = inv.Product__c
                    );
                    inventHistory.add(newInventoryHistory);
                }
            }
        }
        insert inventHistory;
    }
}